apiVersion: apps/v1
kind: Deployment
metadata:
  name: mardan-backend
  namespace: mardan-city
  labels:
    app: mardan-backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mardan-backend
  template:
    metadata:
      labels:
        app: mardan-backend
        tier: backend
    spec:
      containers:
        - name: backend
          image: shoaibikhandev/mardan-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
